"""crear tablas gestion proyectos

Revision ID: 57b884e79e55
Revises: 
Create Date: 2026-09-13 18:14:56.908566

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57b884e79e55'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proyectos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_eliminacion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('propietario_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('icono', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['propietario_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('propietario_id', 'slug', name='uq_proyectos_propietario_slug')
    )
    op.create_index(op.f('ix_proyectos_propietario_id'), 'proyectos', ['propietario_id'], unique=False)
    op.create_index(op.f('ix_proyectos_slug'), 'proyectos', ['slug'], unique=False)
    op.create_table('proyectos_favoritos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_eliminacion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('usuario_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('proyecto_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['proyecto_id'], ['proyectos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'proyecto_id', name='uq_proyectos_favoritos_usuario_proyecto')
    )
    op.create_index(op.f('ix_proyectos_favoritos_proyecto_id'), 'proyectos_favoritos', ['proyecto_id'], unique=False)
    op.create_index(op.f('ix_proyectos_favoritos_usuario_id'), 'proyectos_favoritos', ['usuario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_proyectos_favoritos_usuario_id'), table_name='proyectos_favoritos')
    op.drop_index(op.f('ix_proyectos_favoritos_proyecto_id'), table_name='proyectos_favoritos')
    op.drop_table('proyectos_favoritos')
    op.drop_index(op.f('ix_proyectos_slug'), table_name='proyectos')
    op.drop_index(op.f('ix_proyectos_propietario_id'), table_name='proyectos')
    op.drop_table('proyectos')
    # ### end Alembic commands ###
