from abc import ABC, abstractmethod
from uuid import UUID
from app.modules.diagramas.domain.entities.atributo import Atributo


class AtributoRepository(ABC):
    @abstractmethod
    def obtener_por_id(self, atributo_id: UUID) -> Atributo | None: ...
    @abstractmethod
    def listar_por_clase(self, clase_id: UUID) -> list[Atributo]: ...
    @abstractmethod
    def listar_por_diagrama(self, diagrama_id: UUID) -> list[Atributo]: ...
    @abstractmethod
    def guardar(self, atributo: Atributo) -> None: ...
    @abstractmethod
    def guardar_varios(self, atributos: list[Atributo]) -> None: ...
    @abstractmethod
    def eliminar(self, atributo_id: UUID) -> None: ...
    @abstractmethod
    def eliminar_por_clase(self, clase_id: UUID) -> None: ...
    @abstractmethod
    def eliminar_por_diagrama(self, diagrama_id: UUID) -> None: ...
